USE [master]
GO

/****** Object:  Database [FlightServiceDb]    Script Date: 8/5/2022 8:27:00 AM ******/
DROP DATABASE [FlightServiceDb]
GO

/****** Object:  Database [FlightServiceDb]    Script Date: 8/5/2022 8:27:00 AM ******/
CREATE DATABASE [FlightServiceDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FlightServiceDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FlightServiceDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FlightServiceDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FlightServiceDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FlightServiceDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FlightServiceDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FlightServiceDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FlightServiceDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FlightServiceDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FlightServiceDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [FlightServiceDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FlightServiceDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FlightServiceDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FlightServiceDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FlightServiceDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FlightServiceDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FlightServiceDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FlightServiceDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FlightServiceDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FlightServiceDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FlightServiceDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FlightServiceDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FlightServiceDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FlightServiceDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FlightServiceDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FlightServiceDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FlightServiceDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FlightServiceDb] SET RECOVERY FULL 
GO

ALTER DATABASE [FlightServiceDb] SET  MULTI_USER 
GO

ALTER DATABASE [FlightServiceDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FlightServiceDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FlightServiceDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FlightServiceDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FlightServiceDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FlightServiceDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FlightServiceDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FlightServiceDb] SET  READ_WRITE 
GO


USE [FlightServiceDb]
GO

/****** Object:  Table [dbo].[Flights]    Script Date: 8/5/2022 8:46:21 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Flights](
	[Flight_Id] [int] NOT NULL,
	[FlightNumber] [varchar](20) NOT NULL,
	[DepartureDateTime] [datetime] NOT NULL,
	[ArrivalDateTime] [datetime] NOT NULL,
	[DepartureAirport] [varchar](30) NOT NULL,
	[ArrivalAirport] [varchar](30) NOT NULL,
	[MaxCapacity] [int] NOT NULL,
 CONSTRAINT [PK_Flights] PRIMARY KEY CLUSTERED 
(
	[Flight_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

